# Generated by Django 2.1 on 2018-08-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_group_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='alias',
        ),
    ]
