# Generated by Django 2.1 on 2018-08-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_remove_group_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '组', 'verbose_name_plural': '组'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
