# Generated by Django 2.1 on 2018-08-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_auto_20180802_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, max_length=128, verbose_name='别名'),
        ),
    ]
