# Generated by Django 2.1 on 2018-08-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsjob',
            name='action_type',
        ),
    ]
