# Generated by Django 2.1 on 2018-08-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0002_remove_jenkinsjob_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='action_type',
            field=models.ManyToManyField(blank=True, null=True, to='jkmgr.Operation'),
        ),
    ]
