# Generated by Django 2.1 on 2018-08-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0005_auto_20180806_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='default_action_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jkmgr.Operation'),
        ),
        migrations.AlterField(
            model_name='jenkinsjob',
            name='action_list',
            field=models.ManyToManyField(blank=True, related_name='jks_job', to='jkmgr.Operation'),
        ),
    ]
