# Generated by Django 2.1 on 2018-08-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0006_auto_20180806_0412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jenkinsjob',
            unique_together={('job_name', 'jenkins_server')},
        ),
    ]
