# Generated by Django 2.1 on 2018-08-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0007_auto_20180806_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='svn_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='jenkinsserver',
            name='svn_xml_template',
            field=models.TextField(null=True),
        ),
    ]
