# Generated by Django 2.1 on 2018-08-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0011_jenkinsserver_mavne_job_xml_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsserver',
            name='job_xml_template',
        ),
    ]
