# Generated by Django 2.1 on 2018-08-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0012_remove_jenkinsserver_job_xml_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenkinsjob',
            name='svn_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
