# Generated by Django 2.1 on 2018-08-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jkmgr', '0013_auto_20180809_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenkinsjob',
            name='environment',
        ),
    ]
