# Generated by Django 2.1 on 2018-08-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpinfo', '0009_auto_20180808_0137'),
        ('jkmgr', '0014_remove_jenkinsjob_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsjob',
            name='default_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpinfo.Environment'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='environment_list',
            field=models.ManyToManyField(blank=True, related_name='job_list', to='dpinfo.Environment'),
        ),
    ]
