# Generated by Django 2.1 on 2018-08-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='app_variables',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='db_variables',
        ),
        migrations.AddField(
            model_name='appvariables',
            name='envirment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpinfo.Environment'),
        ),
        migrations.AddField(
            model_name='dbvariables',
            name='envirment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpinfo.Environment'),
        ),
    ]
