# Generated by Django 2.1 on 2018-08-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpinfo', '0002_auto_20180802_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostenvironmentrelation',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
