# Generated by Django 2.1 on 2018-08-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpinfo', '0004_auto_20180803_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appvariables',
            old_name='envirment',
            new_name='environment',
        ),
        migrations.RenameField(
            model_name='dbvariables',
            old_name='envirment',
            new_name='environment',
        ),
    ]
