# Generated by Django 2.1 on 2018-08-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpinfo', '0005_auto_20180803_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvariables',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
