# Generated by Django 2.1 on 2018-08-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpinfo', '0006_auto_20180803_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbvariables',
            name='key',
            field=models.CharField(max_length=255, verbose_name='数据库key'),
        ),
    ]
