# Generated by Django 2.1 on 2018-08-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpinfo', '0007_auto_20180803_0523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostenvironmentrelation',
            unique_together={('environment', 'group', 'project', 'group_type')},
        ),
    ]
